name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Adjust if using a different default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: sreenastc/docker-test:latest
